# Generated by Django 5.0.4 on 2025-07-27 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
        ('posts', '0003_remove_foto_url_foto_foto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.articulo'),
        ),
    ]
